In [1]:
import graphlab

In [2]:
import os

In [3]:
os.chdir("c:/dellbackup/all things data science/datasets/")

In [4]:
sales = graphlab.SFrame("kc_house_data.gl/")

This non-commercial license of GraphLab Create for academic use is assigned to rm83234n@pace.edu and will expire on September 18, 2017.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\Raisa\AppData\Local\Temp\graphlab_server_1478828842.log.0


In [5]:
import numpy as np

In [6]:
#IN ORDER TO CONVERT TO A NUMPY ARRAY
def get_numpy_data(data_sframe, features, output): #check the notebook where you usually breakdown the program to see what exactly this function has been doing
    data_sframe["constant"] = 1 #this is how you add a constant column to an SFrame
    features = ["constant"] + features # the result is features = ["constant","sqft_living"],add the column constant to the front of features list so that we can extract it along with others
    #select the columns of data_sframe given by the features list into sframes
    features_sframe = data_sframe[features]#what you were doing wrong is this data_sframe["feature"] There should be no inverted commas since features is not a column
    #the following line will convert features_sframe to a numpy mtrix
    feature_matrix = features_sframe.to_numpy()
    #assign the column of data_sframe associated with the outpt to the SArray otput_sarray
    output_sarray = data_sframe[output] #here output is sales["price"]
    # the following will convert the SArray into a numpy array by first converting it to a list
    output_array = output_sarray.to_numpy()
    return (feature_matrix, output_array)

In [7]:
sales.head()

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	int
	floors	str
	waterfront	int
	view	int
	condition	int
	grade	int
	sqft_above	int
	sqft_basement	int
	yr_built	int
	yr_renovated	int
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 10

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+------------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade | sqft_above |
+-------------+----------+--------+------------+------+-----------+-------+------------+
|    1180.0   |   5650   |   1    |     0      |  0   |     3     |   7   |    1180    |
|    2570.0   |   7242   |   2    |     0      |  0   |     3     |   7   |    2170    |
|    770.0    |  10000   |   1    |     0      |  0   |     3     |   6   |    770     |
|    1960.0   |   5000   |   1    |     0      |  0   |     5     |   7   |    1050    |
|    1680.0   |   8080   |   1    |     0      |  0   |     3     |   8   |    1680    |
|    5420.0   |  101930  |   1    |     0      |  0   |     3     |   11  |    3890    |
|    1715.0   |   6819   |   2    |     0      |  0   |     3     |   7   |    1715    |
|    1060.0   |   9711   |   1    |     0      |  0   |     3     |   7   |    1060    |
|    1780.0   |   7470   |   1    |     0      |  0   |     3     |   7   |    1050    |
|    1890.0   |   6560   |   2    |     0      |  0   |     3     |   7   |    1890    |
+-------------+----------+--------+------------+------+-----------+-------+------------+
+---------------+----------+--------------+---------+-------------+
| sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+---------------+----------+--------------+---------+-------------+
|       0       |   1955   |      0       |  98178  | 47.51123398 |
|      400      |   1951   |     1991     |  98125  | 47.72102274 |
|       0       |   1933   |      0       |  98028  | 47.73792661 |
|      910      |   1965   |      0       |  98136  |   47.52082  |
|       0       |   1987   |      0       |  98074  | 47.61681228 |
|      1530     |   2001   |      0       |  98053  | 47.65611835 |
|       0       |   1995   |      0       |  98003  | 47.30972002 |
|       0       |   1963   |      0       |  98198  | 47.40949984 |
|      730      |   1960   |      0       |  98146  | 47.51229381 |
|       0       |   2003   |      0       |  98038  | 47.36840673 |
+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |
| -122.32704857 

In [8]:
(example_features, example_output) = get_numpy_data(sales,["sqft_living"], "price") #there is a square bracket around sqft_living to indicate that this is a list

In [9]:
print example_features[0,:] #first row and all columns ':' denotes all 

[  1.00000000e+00   1.18000000e+03]


In [10]:
print example_output[0]

221900.0


In [11]:
#predicting outputs given regression weights
my_weights = np.array([1.,1.]) #the example weights
my_features = example_features[0,] #we will use the first data point
predicted_value = np.dot(my_features,my_weights)

In [12]:
print predicted_value

1181.0


In [13]:
def predict_output(feature_matrix,weights):
    predictions = np.dot(feature_matrix, weights)
    return (predictions)
    

In [14]:
#testing the above function
test_predictions = predict_output(example_features, my_weights)

In [15]:
print test_predictions[0]

1181.0


In [16]:
print test_predictions[1]

2571.0


In [17]:
#works fine, moving on to computation of the derivative

In [18]:
def feature_derivative(errors, feature):
    derivative = np.dot(errors, feature)
    derivative = 2 * derivative
    return (derivative)

In [19]:
#testing whether the above function works correctly
(example_features, example_output) = get_numpy_data(sales, ["sqft_living"], "price")
my_weights = np.array([0.,0.]) #this makes all the predicions zero
test_predictions = predict_output(example_features, my_weights)
errors = test_predictions - example_output
feature = example_features[:,0] #computing the derivative w.r.t constant
derivative = feature_derivative(errors,feature)
print derivative

-23345850022.0


In [20]:
print -np.sum(example_output) * 2 #should be the same as derivative

-23345850022.0


In [21]:
from math import sqrt #because magnitude/ length of a vector [g[0], g[1], g[2]] is sqrt(g[0]^2 + g[1]^2 + g[2]^2)

In [22]:
def regression_gradient_descent(feature_matrix, output, initial_weight, step_size, tolerance):
    converged = False
    weights = np.array(initial_weight) #to make sure it's a numpy array
    while not converged:
        predictions = predict_output(feature_matrix, weights)
        errors = predictions - output #notable step
        gradient_sum_squares = 0
        for i in range(len(weights)): #kryptonite
            derivative = feature_derivative(errors,feature_matrix[:,i])
            squared_derivative = derivative * derivative
            gradient_sum_squares += squared_derivative
            weights[i] -= (step_size * derivative)
        gradient_magnitude = sqrt(gradient_sum_squares)
        if gradient_magnitude < tolerance:
            converged = True
    return (weights)
            
            
            
        

In [23]:
train_data,test_data = sales.random_split(.8,seed=0)

In [24]:
simple_features = ["sqft_living"]

In [25]:
my_output = "price"

In [26]:
(simple_feature_matrix, output) = get_numpy_data(train_data,simple_features, my_output)

In [27]:
initial_weights = np.array([-47000.,1.])

In [28]:
step_size = 7e-12

In [29]:
tolerance = 2.5e7

In [31]:
model_1  = regression_gradient_descent(simple_feature_matrix,output, initial_weights, step_size, tolerance)

In [34]:
model_1

array([-46999.88716555,    281.91211912])

In [33]:
simple_feature_matrix[1]

array([  1.00000000e+00,   2.57000000e+03])

In [36]:
predict_output(simple_feature_matrix, model_1)[1]

677514.25896364427

In [37]:
(test_simple_feature_matrix, test_output) = get_numpy_data(test_data,simple_features,my_output)

In [39]:
predict_output(test_simple_feature_matrix, model_1)[0]

356134.44317092974

In [40]:
def RSS(errors):
    return errors ** 2

In [41]:
test_predictions = predict_output(test_simple_feature_matrix, model_1)

In [43]:
errors = test_predictions - test_output

In [44]:
RSS = RSS(errors)

In [47]:
RSS.sum()

275400047593155.94

In [48]:
#running a multiple regression
model_features = ["sqft_living", "sqft_living15"]

In [49]:
my_output = "price"

In [50]:
(feature_matrix, output) = get_numpy_data(train_data,model_features, my_output)

In [51]:
initial_weights = np.array([-100000.,1.,1.])


In [52]:
step_size = 4e-12


In [53]:
tolerance = 1e9

In [54]:
model_2 = regression_gradient_descent(feature_matrix, output, initial_weights,step_size,tolerance)

In [55]:
model_2

array([ -9.99999688e+04,   2.45072603e+02,   6.52795277e+01])

In [56]:
(test_feature_matrix, test_model_2_output) = get_numpy_data(test_data, model_features, my_output)

In [57]:
test_predictions_2 = predict_output(test_feature_matrix,model_2)

In [58]:
test_predictions_2[0]

366651.41203655908

In [59]:
sales[0]

{'bathrooms': 1.0,
 'bedrooms': 3.0,
 'condition': 3L,
 'constant': 1L,
 'date': datetime.datetime(2014, 10, 13, 0, 0, tzinfo=GMT +0.0),
 'floors': '1',
 'grade': 7L,
 'id': '7129300520',
 'lat': 47.51123398,
 'long': -122.25677536,
 'price': 221900.0,
 'sqft_above': 1180L,
 'sqft_basement': 0L,
 'sqft_living': 1180.0,
 'sqft_living15': 1340.0,
 'sqft_lot': 5650L,
 'sqft_lot15': 5650.0,
 'view': 0L,
 'waterfront': 0L,
 'yr_built': 1955L,
 'yr_renovated': 0L,
 'zipcode': '98178'}

In [61]:
test_data[0]

{'bathrooms': 1.0,
 'bedrooms': 3.0,
 'condition': 4L,
 'constant': 1L,
 'date': datetime.datetime(2014, 5, 28, 0, 0, tzinfo=GMT +0.0),
 'floors': '1.5',
 'grade': 7L,
 'id': '0114101516',
 'lat': 47.75584254,
 'long': -122.22874498,
 'price': 310000.0,
 'sqft_above': 1430L,
 'sqft_basement': 0L,
 'sqft_living': 1430.0,
 'sqft_living15': 1780.0,
 'sqft_lot': 19901L,
 'sqft_lot15': 12697.0,
 'view': 0L,
 'waterfront': 0L,
 'yr_built': 1927L,
 'yr_renovated': 0L,
 'zipcode': '98028'}

In [62]:
errors_2 = test_predictions_2 - test_model_2_output


In [66]:
errors_2

array([  56651.41203656,  112662.39786164,  153312.09499712, ...,
         71402.39928241,  185579.27865729, -185541.79603383])

In [69]:
RSS = errors_2 * errors_2

In [70]:
RSS.sum()

270263446465244.06